name: Automatic Release 🤖
run-name: Publish version ${{ github.ref_name }}

on:
  push:
    tags:
      - "dev-[0-9]+.[0-9]+.[0-9]+"

jobs:
  get_version:
    outputs:
      version: ${{ steps.version.outputs.substring }}
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: version
        with:
          value: ${{ github.ref_name }}
          index_of_str: "dev-"
  export_game_release:
    name: Publish version ${{ github.ref_name }} 🤖
    needs: [get_version]
    uses: ./.github/workflows/build-and-upload.yml
    with:
      project_name: ${{ vars.PRIVATE_PROJECT_NAME }}
      version: v${{ needs.get_version.outputs.version }} # ${{ github.ref_name }}
    secrets:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
