name: Automatic Release 🤖
run-name: Publish version ${{ github.ref_name }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  export_game_release:
    name: Publish version ${{ github.ref_name }} 🤖
    uses: ./.github/workflows/build-and-upload.yml
    with:
      project_name: ${{ vars.PUBLIC_PROJECT_NAME }}
      version: ${{ github.ref_name }}
    secrets:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
